name: Build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.403'
      - name: Restore Packages
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Run Tests
        env:
          BROWSER_DRIVER_HEADLESS: 1
          BROWSER_DRIVER_WINDOW_SIZE: 1024x768
        run: dotnet test --no-build --configuration Release --logger junit --test-adapter-path .
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: |
            TestResults/
